# Generated by Django 3.0 on 2020-01-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_archivalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comments_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archivalmodel',
            name='post_comments',
            field=models.ManyToManyField(to='posts.CommentsModel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_comments',
            field=models.ManyToManyField(to='posts.CommentsModel'),
        ),
    ]
