# Generated by Django 3.0 on 2020-01-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200111_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='post_comments',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.PostModel'),
            preserve_default=False,
        ),
    ]
