# Generated by Django 3.0 on 2020-01-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200112_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.PostModel'),
        ),
    ]
