# Generated by Django 3.0 on 2020-01-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postmodelhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalmodel',
            name='post_comments',
        ),
        migrations.DeleteModel(
            name='PostModelHistory',
        ),
    ]
