# Generated by Django 3.0 on 2020-01-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postmodelhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModelHistory',
        ),
    ]
