# Generated by Django 3.0 on 2020-01-23 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_delete_postmodelhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_area_edited', models.TextField()),
                ('history_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
