# Generated by Django 3.0 on 2020-01-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_postmodelhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodelhistory',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_history', to='posts.PostModel'),
            preserve_default=False,
        ),
    ]
