# Generated by Django 3.0 on 2020-01-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200123_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodelhistory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posthistory', to='posts.PostModel'),
        ),
    ]
