# Generated by Django 3.0 on 2020-01-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20200124_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='comments_date',
            new_name='comment_date',
        ),
    ]
