# Generated by Django 3.0 on 2020-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
