# Generated by Django 3.0 on 2020-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200227_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
