# Generated by Django 3.0 on 2020-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200303_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_img',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='topic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
